# Generated by Django 5.2.11 on 2026-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_visitor_country_visitor_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
