# Generated by Django 5.2.11 on 2026-03-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountChart',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('acc_account_number', models.IntegerField()),
                ('acc_account_name', models.CharField(max_length=25)),
                ('acc_class_level_2', models.IntegerField()),
                ('acc_class_level_3', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_accounts_chart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountChartTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_account_number', models.IntegerField()),
                ('acc_account_name', models.CharField(max_length=25)),
                ('acc_class_level_2', models.IntegerField()),
                ('acc_class_level_3', models.IntegerField()),
            ],
            options={
                'db_table': 'sources_accounts_chart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsChartAssoTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'sources_accounts_chart_asso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=150)),
                ('is_active', models.IntegerField(default=1)),
                ('admin_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_announcements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=50)),
                ('company_fone', models.CharField(max_length=50)),
                ('company_adress', models.CharField(max_length=100)),
                ('company_cc', models.CharField(default='1234567A', max_length=20)),
                ('company_cnps_number', models.CharField(default='111111', max_length=20)),
                ('company_rccm', models.CharField(default='RCCM-000000000', max_length=20)),
                ('company_logo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_company_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_status', models.IntegerField(default=1)),
                ('cust_plan', models.IntegerField(verbose_name=11)),
                ('cust_subscrip_duration', models.IntegerField(default=12)),
                ('cust_identifiant', models.CharField(max_length=200)),
                ('cust_slug', models.CharField(max_length=200)),
                ('cust_company_name', models.CharField(max_length=250)),
                ('cust_fone', models.CharField(max_length=20)),
                ('cust_start_date', models.DateTimeField(auto_now_add=True)),
                ('cust_email', models.CharField(max_length=50)),
                ('cust_connect_statut', models.IntegerField(default=0)),
                ('cust_ip', models.CharField(max_length=200)),
                ('admin_code', models.CharField(default=1, max_length=10)),
                ('cust_end_subscription', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerConnect',
            fields=[
                ('cust_connect_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_current', models.CharField(max_length=200)),
                ('cust_user_time_connect', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adminapp_customerconnect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpendType',
            fields=[
                ('et_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('et_account_nb', models.IntegerField()),
                ('et_account_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tbl_expend_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpendTypeAssoTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('et_account_nb', models.IntegerField()),
                ('et_account_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'sources_expend_types_asso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpendTypeTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('et_account_nb', models.IntegerField()),
                ('et_account_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'sources_expend_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListJrx',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('journal_code', models.CharField(max_length=20)),
                ('journal_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tbl_list_jrx',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListJrxTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('journal_code', models.CharField(max_length=11)),
                ('journal_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'sources_list_jrx',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField()),
                ('module_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayParameters',
            fields=[
                ('pp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('pp_cmu', models.CharField(default='NON', max_length=3)),
                ('pp_anciennete', models.CharField(default='NON', max_length=3)),
                ('pp_cnps_tx', models.IntegerField()),
                ('pp_pay_rounded', models.CharField(default='NON', max_length=3)),
            ],
            options={
                'db_table': 'tbl_pay_parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roles_id', models.IntegerField(primary_key=True, serialize=False)),
                ('roles_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdAccount',
            fields=[
                ('third_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('third_type', models.CharField(max_length=11)),
                ('third_name', models.CharField(max_length=25)),
                ('third_slug_name', models.CharField(max_length=25)),
                ('third_ncc', models.CharField(max_length=11)),
                ('third_rccm', models.CharField(max_length=25)),
                ('third_adress', models.CharField(max_length=11)),
                ('third_fone', models.CharField(max_length=25)),
                ('third_email', models.CharField(max_length=25)),
                ('third_interl_function_1', models.CharField(max_length=50)),
                ('third_interlocuteur_1', models.CharField(max_length=100)),
                ('third_interl_contact_1', models.CharField(max_length=11)),
                ('third_interl_email_1', models.CharField(max_length=25)),
                ('third_interl_function_2', models.CharField(max_length=50)),
                ('third_interlocuteur_2', models.CharField(max_length=100)),
                ('third_interl_contact_2', models.CharField(max_length=11)),
                ('third_interl_email_2', models.CharField(max_length=25)),
                ('third_account', models.IntegerField(verbose_name=11)),
                ('third_payement_ddl', models.IntegerField(verbose_name=11)),
                ('third_others_infos', models.CharField(max_length=250)),
                ('third_status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_third_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdAccountTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('third_type', models.CharField(max_length=11)),
                ('third_name', models.CharField(max_length=25)),
                ('third_ncc', models.CharField(max_length=11)),
                ('third_rccm', models.CharField(max_length=25)),
                ('third_adress', models.CharField(max_length=11)),
                ('third_fone', models.CharField(max_length=25)),
                ('third_email', models.CharField(max_length=25)),
                ('third_interl_function_1', models.CharField(max_length=50)),
                ('third_interlocuteur_1', models.CharField(max_length=100)),
                ('third_interl_contact_1', models.CharField(max_length=11)),
                ('third_interl_email_1', models.CharField(max_length=25)),
                ('third_account', models.IntegerField(verbose_name=11)),
                ('third_payement_ddl', models.IntegerField(verbose_name=11)),
                ('third_others_infos', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'sources_third_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_read', models.IntegerField()),
                ('dismissed', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_user_announcements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserConnect',
            fields=[
                ('connect_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('user_times_connect', models.DateTimeField()),
                ('user_ip', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'tbl_users_connect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('perm_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('roles_id', models.IntegerField()),
                ('module_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_user_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('empl_id', models.IntegerField()),
                ('user_pseudo', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_users_py',
                'managed': False,
            },
        ),
    ]
