# Generated by Django 5.2.11 on 2026-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelechargementFinCompta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(db_index=True, max_length=30)),
                ("fichier", models.CharField(max_length=120)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "téléchargement de FinCompta",
                "verbose_name_plural": "téléchargements de FinCompta",
                "ordering": ["-date"],
            },
        ),
    ]
